# Generated by Django 2.2.3 on 2019-07-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermembership',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user_membership',
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(blank=True, default=15),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_plan',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'MONTH'), ('YEARLY', 'YEAR')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='UserMembership',
        ),
    ]
