# Generated by Django 2.2.3 on 2019-07-30 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20190730_0733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='price',
            new_name='ammount',
        ),
    ]
