# Generated by Django 2.2.3 on 2019-07-31 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190730_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='ammount',
            field=models.IntegerField(blank=True, default=150),
        ),
    ]
